# Generated by Django 4.2.1 on 2023-05-10 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='payRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('recipient', models.CharField(max_length=45)),
                ('amount', models.IntegerField()),
                ('money', models.FloatField()),
                ('secret_key', models.CharField(max_length=45)),
                ('userId', models.IntegerField()),
                ('airline_order', models.CharField(max_length=45)),
                ('state', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('deposit', models.FloatField()),
                ('name', models.CharField(max_length=10)),
            ],
        ),
    ]
